version: '3.8'

services:
  spring-boot-app:
    image: spring
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "9090:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpw

    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:





